[package]
name = "cassandra_test"
version = "0.1.0"
edition = "2021"

# See more keys and their definitions at https://doc.rust-lang.org/cargo/reference/manifest.html

[dependencies]
cassandra-cpp = "2.0.0"
tokio = { version = "1.28.1", features = ["macros", "rt"] }
